// <auto-generated />
namespace Week6.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntityIDfieldadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityIDfieldadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201810232239260_Entity ID field added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
